version: "3"
services:
  mongodb:
    image: mongo:latest
  #  environment:
  #    MONGO_INITDB_DATABASE: user
    container_name: mongodb
    command: mongod --port 27018
  #  restart: always
    ports:
      - 27018:27018
  #  volumes:
  #    - mongodb_data_container:/data/db
  user-service:
    image: user:0.0.1-SNAPSHOT
    container_name: user-service
    ports:
      - 8080:8080
    environment:
      MONGOHOST: mongodb
    #links:
    #  - mongodb

volumes:
  mongodb_data_container: