version: "3"
services:
  mongodb:
    image: mongo:latest
  #  environment:
  #    MONGO_INITDB_DATABASE: user
    container_name: mongodb
    command: mongod --port 27018
  #  restart: always
    ports:
      - 27018:27018
  #  volumes:
  #    - mongodb_data_container:/data/db
  user-service:
    image: user:0.0.1-SNAPSHOT
    container_name: user-service
    ports:
      - 8080:8080
    environment:
      MONGOHOST: mongodb
    links:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - user-service
      - mongodb

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    #volumes:
    #  - ./grafana:/var/lib/grafana
    user: '472'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password


volumes:
  mongodb_data_container: