global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluvate rules every 5 sec

rule_files:
# - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['127.0.0.1:8080']
      - targets: ['127.0.0.1:8080']

